# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: b31907eb0d2feb8e295f5e8fdef92c4ed206b132495bd959fc0a6116d6d17594f31bf64641b0626ca7a3f55eb7bc267f15050b7a281e4a713e58eb79f30bec42

test:
  domain_name: example.com 
  secret_key_base: 967676c2c658219a1247f235f808f2bc865cc3e441195403c9d3c14cf511cd711f9cebc1ab10de05f36dc98709cf8005d2052ae43dcdb18615fc7926d6c3af3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
